version: '3'
services:
  classplay:
    build: .
    container_name: classplay
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./edugames.db:/app/edugames.db
    environment:
      - PORT=3000
      - NODE_ENV=production
