version: '3'
services:
  classplay:
    build: .
    container_name: classplay
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./edugames.db:/app/edugames.db
    environment:
      - PORT=3000
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
